#cloud-config

disk_setup:
  /dev/sdb:
    table_type: gpt
    layout: true
    overwrite: false

fs_setup:
  - label: logs
    filesystem: ext4
    device: /dev/sdb
    partition: auto

mounts:
    - [ /dev/disk/by-label/logs, /var/log, ext4, "defaults,nofail", "0", "0" ]

yum_repos:
  docker:
    baseurl: https://download.docker.com/linux/centos/9/$basearch/stable
    gpgcheck: yes
    gpgkey: https://download.docker.com/linux/centos/gpg
    name: Docker CE Stable - $basearch
    enabled: yes

packages:
  - docker-ce
  - docker-ce-cli
  - containerd.io

runcmd:
  - systemctl daemon-reload
  - systemctl enable docker
  - systemctl start --no-block docker
