#cloud-config

device_aliases:
  ephemeral0: '/dev/disk/by-path/pci-0000:03:00.0-scsi-0:0:1:0'

disk_setup:
  ephemeral0:
    table_type: gpt
    layout: true

fs_setup:
  - label: logs
    filesystem: ext4
    device: ephemeral0.1

mounts:
    - [ ephemeral0.1, /var/log, ext4, "defaults,nofail", "0", "0" ]

yum_repos:
  docker:
    baseurl: https://download.docker.com/linux/centos/9/$basearch/stable
    gpgcheck: yes
    gpgkey: https://download.docker.com/linux/centos/gpg
    name: Docker CE Stable - $basearch
    enabled: yes

packages:
  - docker-ce
  - docker-ce-cli
  - containerd.io

runcmd:
  - systemctl daemon-reload
  - systemctl enable docker
  - systemctl start --no-block docker
